#:schema node_modules/wrangler/config-schema.json
name = "teletekst"
main = "src/index.ts"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "tt.appelman.se", custom_domain = true }
]
workers_dev = false

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "3d1c1c9461d4438e88df1cf7c9fc022c"

[triggers]
crons = [ "*/30 * * * *"]

